# Generated by Django 3.0.2 on 2020-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotopage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=100)),
            ],
        ),
    ]
