# Generated by Django 3.0.2 on 2020-02-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotopage', '0002_lightbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lightbox',
        ),
    ]
