# Generated by Django 3.0.2 on 2020-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotopage', '0003_delete_lightbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
