# Generated by Django 3.0.2 on 2020-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotopage', '0004_lightbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lightbox',
        ),
    ]
