# Generated by Django 3.0.2 on 2020-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotopage', '0006_album_lightbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priceofwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lightbox',
            name='alt',
            field=models.CharField(default='Photo_Ksenia_Sheen', max_length=255),
        ),
    ]
